spring:
  application:
    name: warehouse-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/sklad
    username: warehouse
    password: warehouse
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false

server:
  port: 8080
